# Generated by Django 5.0.4 on 2024-04-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customer_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_img',
        ),
    ]
